# TCL File Generated by Component Editor 16.0
# Sun Aug 13 21:15:43 CST 2017
# DO NOT MODIFY


# 
# matrix_mult_det "matrix_mult_det" v1.0
#  2017.08.13.21:15:43
# 
# 

# 
# request TCL package from ACDS 16.0
# 
package require -exact qsys 16.0


# 
# module matrix_mult_det
# 
set_module_property DESCRIPTION ""
set_module_property NAME matrix_mult_det
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME matrix_mult_det
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL IP_matrix_2x2_multiplier_determinant
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file IP_matrix_2x2_multiplier_determinant.v VERILOG PATH IP_matrix_2x2_multiplier_determinant.v TOP_LEVEL_FILE
add_fileset_file matrix_2x2_multiplier_determinant.v VERILOG PATH matrix_2x2_multiplier_determinant.v

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL IP_matrix_2x2_multiplier_determinant
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file IP_matrix_2x2_multiplier_determinant.v VERILOG PATH IP_matrix_2x2_multiplier_determinant.v
add_fileset_file matrix_2x2_multiplier_determinant.v VERILOG PATH matrix_2x2_multiplier_determinant.v


# 
# parameters
# 
add_parameter DATA_REG_1 STD_LOGIC_VECTOR 0
set_parameter_property DATA_REG_1 DEFAULT_VALUE 0
set_parameter_property DATA_REG_1 DISPLAY_NAME DATA_REG_1
set_parameter_property DATA_REG_1 TYPE STD_LOGIC_VECTOR
set_parameter_property DATA_REG_1 UNITS None
set_parameter_property DATA_REG_1 ALLOWED_RANGES 0:7
set_parameter_property DATA_REG_1 HDL_PARAMETER true
add_parameter DATA_REG_2 STD_LOGIC_VECTOR 1
set_parameter_property DATA_REG_2 DEFAULT_VALUE 1
set_parameter_property DATA_REG_2 DISPLAY_NAME DATA_REG_2
set_parameter_property DATA_REG_2 TYPE STD_LOGIC_VECTOR
set_parameter_property DATA_REG_2 UNITS None
set_parameter_property DATA_REG_2 ALLOWED_RANGES 0:7
set_parameter_property DATA_REG_2 HDL_PARAMETER true
add_parameter CONTROL_REG STD_LOGIC_VECTOR 2
set_parameter_property CONTROL_REG DEFAULT_VALUE 2
set_parameter_property CONTROL_REG DISPLAY_NAME CONTROL_REG
set_parameter_property CONTROL_REG TYPE STD_LOGIC_VECTOR
set_parameter_property CONTROL_REG UNITS None
set_parameter_property CONTROL_REG ALLOWED_RANGES 0:7
set_parameter_property CONTROL_REG HDL_PARAMETER true
add_parameter OUT_REG STD_LOGIC_VECTOR 3
set_parameter_property OUT_REG DEFAULT_VALUE 3
set_parameter_property OUT_REG DISPLAY_NAME OUT_REG
set_parameter_property OUT_REG TYPE STD_LOGIC_VECTOR
set_parameter_property OUT_REG UNITS None
set_parameter_property OUT_REG ALLOWED_RANGES 0:7
set_parameter_property OUT_REG HDL_PARAMETER true


# 
# display items
# 


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock_sink
set_interface_property avalon_slave_0 associatedReset reset_sink
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitStates 0
set_interface_property avalon_slave_0 readWaitTime 0
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 writedata writedata Input 32
add_interface_port avalon_slave_0 readdata readdata Output 32
add_interface_port avalon_slave_0 write write Input 1
add_interface_port avalon_slave_0 read read Input 1
add_interface_port avalon_slave_0 chipselect chipselect Input 1
add_interface_port avalon_slave_0 in_address address Input 2
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink clock clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink reset reset Input 1

